---
# This task will download the provider repositories and install their actions

- set_fact:
    provider_location={{ item.value.location }}
    provider_repo_url={{ item.value.url }}
    edge_host={{ groups['edge'] | first }}
    version="HEAD"
    repo_update="yes"
    api_host={{ whisk_api_host_name | default(groups['edge'] | first) }}
    db_url="{{ db_protocol }}://{{ db_username }}:{{ db_password }}@{{ db_host }}:{{ db_port }}"

- set_fact:
    version={{ item.value.version }}
  when: item.value.version is defined

- set_fact:
    repo_update={{ item.value.repo_update }}
  when: item.value.repo_update is defined

- name: download the provider repository to the provider location if necessary
  git:
    depth: 1
    repo: "{{ provider_repo_url }}"
    dest: "{{ provider_location }}"
    update: "{{ repo_update }}"
    version: "{{ version }}"

- name: install the actions from the provider location
  shell: ./installCatalog.sh {{ catalog_auth_key }} {{ edge_host }} {{ db_url }} {{ db_prefix }} {{ api_host }} chdir={{ provider_location }}
  environment:
    OPENWHISK_HOME: "{{ openwhisk_home }}"
